// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC09Xw2siaDk1LOnutgdJpkdGYBCzl6Iiw',
    appId: '1:30792764859:web:3b0d06d43de93be920889e',
    messagingSenderId: '30792764859',
    projectId: 'baby-buy-87cf3',
    authDomain: 'baby-buy-87cf3.firebaseapp.com',
    storageBucket: 'baby-buy-87cf3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5akR4AQyHdAEV-7vPgxLXRRV37NMpZRg',
    appId: '1:30792764859:android:17e1e5d83710259d20889e',
    messagingSenderId: '30792764859',
    projectId: 'baby-buy-87cf3',
    storageBucket: 'baby-buy-87cf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV_qGYp6gAPRCIUqpS2ZMU0Okp-IV5Wi8',
    appId: '1:30792764859:ios:e91d94145a9bb85f20889e',
    messagingSenderId: '30792764859',
    projectId: 'baby-buy-87cf3',
    storageBucket: 'baby-buy-87cf3.firebasestorage.app',
    iosBundleId: 'com.example.babyBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV_qGYp6gAPRCIUqpS2ZMU0Okp-IV5Wi8',
    appId: '1:30792764859:ios:e91d94145a9bb85f20889e',
    messagingSenderId: '30792764859',
    projectId: 'baby-buy-87cf3',
    storageBucket: 'baby-buy-87cf3.firebasestorage.app',
    iosBundleId: 'com.example.babyBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC09Xw2siaDk1LOnutgdJpkdGYBCzl6Iiw',
    appId: '1:30792764859:web:7674087e94a4a02a20889e',
    messagingSenderId: '30792764859',
    projectId: 'baby-buy-87cf3',
    authDomain: 'baby-buy-87cf3.firebaseapp.com',
    storageBucket: 'baby-buy-87cf3.firebasestorage.app',
  );
}
